/*
 * generated by Xtext 2.25.0
 */
package pret.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyDslUiModule extends AbstractMyDslUiModule {

	public MyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
