/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pret.myDsl.Definition#getDefInput <em>Def Input</em>}</li>
 *   <li>{@link pret.myDsl.Definition#getDefCommands <em>Def Commands</em>}</li>
 *   <li>{@link pret.myDsl.Definition#getDefOutput <em>Def Output</em>}</li>
 * </ul>
 *
 * @see pret.myDsl.MyDslPackage#getDefinition()
 * @model
 * @generated
 */
public interface Definition extends EObject
{
  /**
   * Returns the value of the '<em><b>Def Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def Input</em>' containment reference.
   * @see #setDefInput(Input)
   * @see pret.myDsl.MyDslPackage#getDefinition_DefInput()
   * @model containment="true"
   * @generated
   */
  Input getDefInput();

  /**
   * Sets the value of the '{@link pret.myDsl.Definition#getDefInput <em>Def Input</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Def Input</em>' containment reference.
   * @see #getDefInput()
   * @generated
   */
  void setDefInput(Input value);

  /**
   * Returns the value of the '<em><b>Def Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def Commands</em>' containment reference.
   * @see #setDefCommands(Commands)
   * @see pret.myDsl.MyDslPackage#getDefinition_DefCommands()
   * @model containment="true"
   * @generated
   */
  Commands getDefCommands();

  /**
   * Sets the value of the '{@link pret.myDsl.Definition#getDefCommands <em>Def Commands</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Def Commands</em>' containment reference.
   * @see #getDefCommands()
   * @generated
   */
  void setDefCommands(Commands value);

  /**
   * Returns the value of the '<em><b>Def Output</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def Output</em>' containment reference.
   * @see #setDefOutput(Output)
   * @see pret.myDsl.MyDslPackage#getDefinition_DefOutput()
   * @model containment="true"
   * @generated
   */
  Output getDefOutput();

  /**
   * Sets the value of the '{@link pret.myDsl.Definition#getDefOutput <em>Def Output</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Def Output</em>' containment reference.
   * @see #getDefOutput()
   * @generated
   */
  void setDefOutput(Output value);

} // Definition
