/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EBtl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pret.myDsl.EBtl#getExpb <em>Expb</em>}</li>
 * </ul>
 *
 * @see pret.myDsl.MyDslPackage#getEBtl()
 * @model
 * @generated
 */
public interface EBtl extends EObject
{
  /**
   * Returns the value of the '<em><b>Expb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expb</em>' containment reference.
   * @see #setExpb(ExprBase)
   * @see pret.myDsl.MyDslPackage#getEBtl_Expb()
   * @model containment="true"
   * @generated
   */
  ExprBase getExpb();

  /**
   * Sets the value of the '{@link pret.myDsl.EBtl#getExpb <em>Expb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expb</em>' containment reference.
   * @see #getExpb()
   * @generated
   */
  void setExpb(ExprBase value);

} // EBtl
