/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Base</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pret.myDsl.ExprBase#getNi <em>Ni</em>}</li>
 *   <li>{@link pret.myDsl.ExprBase#getV <em>V</em>}</li>
 *   <li>{@link pret.myDsl.ExprBase#getSy <em>Sy</em>}</li>
 *   <li>{@link pret.myDsl.ExprBase#getEbt <em>Ebt</em>}</li>
 *   <li>{@link pret.myDsl.ExprBase#getEbh <em>Ebh</em>}</li>
 *   <li>{@link pret.myDsl.ExprBase#getEbc <em>Ebc</em>}</li>
 *   <li>{@link pret.myDsl.ExprBase#getEbl <em>Ebl</em>}</li>
 *   <li>{@link pret.myDsl.ExprBase#getEbs <em>Ebs</em>}</li>
 * </ul>
 *
 * @see pret.myDsl.MyDslPackage#getExprBase()
 * @model
 * @generated
 */
public interface ExprBase extends EObject
{
  /**
   * Returns the value of the '<em><b>Ni</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ni</em>' attribute.
   * @see #setNi(String)
   * @see pret.myDsl.MyDslPackage#getExprBase_Ni()
   * @model
   * @generated
   */
  String getNi();

  /**
   * Sets the value of the '{@link pret.myDsl.ExprBase#getNi <em>Ni</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ni</em>' attribute.
   * @see #getNi()
   * @generated
   */
  void setNi(String value);

  /**
   * Returns the value of the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>V</em>' attribute.
   * @see #setV(String)
   * @see pret.myDsl.MyDslPackage#getExprBase_V()
   * @model
   * @generated
   */
  String getV();

  /**
   * Sets the value of the '{@link pret.myDsl.ExprBase#getV <em>V</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V</em>' attribute.
   * @see #getV()
   * @generated
   */
  void setV(String value);

  /**
   * Returns the value of the '<em><b>Sy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sy</em>' attribute.
   * @see #setSy(String)
   * @see pret.myDsl.MyDslPackage#getExprBase_Sy()
   * @model
   * @generated
   */
  String getSy();

  /**
   * Sets the value of the '{@link pret.myDsl.ExprBase#getSy <em>Sy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sy</em>' attribute.
   * @see #getSy()
   * @generated
   */
  void setSy(String value);

  /**
   * Returns the value of the '<em><b>Ebt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ebt</em>' containment reference.
   * @see #setEbt(EBtl)
   * @see pret.myDsl.MyDslPackage#getExprBase_Ebt()
   * @model containment="true"
   * @generated
   */
  EBtl getEbt();

  /**
   * Sets the value of the '{@link pret.myDsl.ExprBase#getEbt <em>Ebt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ebt</em>' containment reference.
   * @see #getEbt()
   * @generated
   */
  void setEbt(EBtl value);

  /**
   * Returns the value of the '<em><b>Ebh</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ebh</em>' containment reference.
   * @see #setEbh(EBhd)
   * @see pret.myDsl.MyDslPackage#getExprBase_Ebh()
   * @model containment="true"
   * @generated
   */
  EBhd getEbh();

  /**
   * Sets the value of the '{@link pret.myDsl.ExprBase#getEbh <em>Ebh</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ebh</em>' containment reference.
   * @see #getEbh()
   * @generated
   */
  void setEbh(EBhd value);

  /**
   * Returns the value of the '<em><b>Ebc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ebc</em>' containment reference.
   * @see #setEbc(EBcons)
   * @see pret.myDsl.MyDslPackage#getExprBase_Ebc()
   * @model containment="true"
   * @generated
   */
  EBcons getEbc();

  /**
   * Sets the value of the '{@link pret.myDsl.ExprBase#getEbc <em>Ebc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ebc</em>' containment reference.
   * @see #getEbc()
   * @generated
   */
  void setEbc(EBcons value);

  /**
   * Returns the value of the '<em><b>Ebl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ebl</em>' containment reference.
   * @see #setEbl(EBlist)
   * @see pret.myDsl.MyDslPackage#getExprBase_Ebl()
   * @model containment="true"
   * @generated
   */
  EBlist getEbl();

  /**
   * Sets the value of the '{@link pret.myDsl.ExprBase#getEbl <em>Ebl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ebl</em>' containment reference.
   * @see #getEbl()
   * @generated
   */
  void setEbl(EBlist value);

  /**
   * Returns the value of the '<em><b>Ebs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ebs</em>' containment reference.
   * @see #setEbs(EBsy)
   * @see pret.myDsl.MyDslPackage#getExprBase_Ebs()
   * @model containment="true"
   * @generated
   */
  EBsy getEbs();

  /**
   * Sets the value of the '{@link pret.myDsl.ExprBase#getEbs <em>Ebs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ebs</em>' containment reference.
   * @see #getEbs()
   * @generated
   */
  void setEbs(EBsy value);

} // ExprBase
