/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Foreach</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pret.myDsl.Foreach#getForevar <em>Forevar</em>}</li>
 *   <li>{@link pret.myDsl.Foreach#getForeexp <em>Foreexp</em>}</li>
 *   <li>{@link pret.myDsl.Foreach#getForecom <em>Forecom</em>}</li>
 * </ul>
 *
 * @see pret.myDsl.MyDslPackage#getForeach()
 * @model
 * @generated
 */
public interface Foreach extends EObject
{
  /**
   * Returns the value of the '<em><b>Forevar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forevar</em>' attribute.
   * @see #setForevar(String)
   * @see pret.myDsl.MyDslPackage#getForeach_Forevar()
   * @model
   * @generated
   */
  String getForevar();

  /**
   * Sets the value of the '{@link pret.myDsl.Foreach#getForevar <em>Forevar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Forevar</em>' attribute.
   * @see #getForevar()
   * @generated
   */
  void setForevar(String value);

  /**
   * Returns the value of the '<em><b>Foreexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foreexp</em>' containment reference.
   * @see #setForeexp(Expression)
   * @see pret.myDsl.MyDslPackage#getForeach_Foreexp()
   * @model containment="true"
   * @generated
   */
  Expression getForeexp();

  /**
   * Sets the value of the '{@link pret.myDsl.Foreach#getForeexp <em>Foreexp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Foreexp</em>' containment reference.
   * @see #getForeexp()
   * @generated
   */
  void setForeexp(Expression value);

  /**
   * Returns the value of the '<em><b>Forecom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forecom</em>' containment reference.
   * @see #setForecom(Commands)
   * @see pret.myDsl.MyDslPackage#getForeach_Forecom()
   * @model containment="true"
   * @generated
   */
  Commands getForecom();

  /**
   * Sets the value of the '{@link pret.myDsl.Foreach#getForecom <em>Forecom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Forecom</em>' containment reference.
   * @see #getForecom()
   * @generated
   */
  void setForecom(Commands value);

} // Foreach
