/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pret.myDsl.Function#getFname <em>Fname</em>}</li>
 *   <li>{@link pret.myDsl.Function#getFdef <em>Fdef</em>}</li>
 * </ul>
 *
 * @see pret.myDsl.MyDslPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends EObject
{
  /**
   * Returns the value of the '<em><b>Fname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fname</em>' attribute.
   * @see #setFname(String)
   * @see pret.myDsl.MyDslPackage#getFunction_Fname()
   * @model
   * @generated
   */
  String getFname();

  /**
   * Sets the value of the '{@link pret.myDsl.Function#getFname <em>Fname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fname</em>' attribute.
   * @see #getFname()
   * @generated
   */
  void setFname(String value);

  /**
   * Returns the value of the '<em><b>Fdef</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fdef</em>' containment reference.
   * @see #setFdef(Definition)
   * @see pret.myDsl.MyDslPackage#getFunction_Fdef()
   * @model containment="true"
   * @generated
   */
  Definition getFdef();

  /**
   * Sets the value of the '{@link pret.myDsl.Function#getFdef <em>Fdef</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fdef</em>' containment reference.
   * @see #getFdef()
   * @generated
   */
  void setFdef(Definition value);

} // Function
