/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pret.myDsl.Input#getVai <em>Vai</em>}</li>
 * </ul>
 *
 * @see pret.myDsl.MyDslPackage#getInput()
 * @model
 * @generated
 */
public interface Input extends EObject
{
  /**
   * Returns the value of the '<em><b>Vai</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vai</em>' attribute list.
   * @see pret.myDsl.MyDslPackage#getInput_Vai()
   * @model unique="false"
   * @generated
   */
  EList<String> getVai();

} // Input
