/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see pret.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.MyDsl.pret";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = pret.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link pret.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.ModelImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Func</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__FUNC = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.FunctionImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 1;

  /**
   * The feature id for the '<em><b>Fname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__FNAME = 0;

  /**
   * The feature id for the '<em><b>Fdef</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__FDEF = 1;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.DefinitionImpl <em>Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.DefinitionImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getDefinition()
   * @generated
   */
  int DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Def Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__DEF_INPUT = 0;

  /**
   * The feature id for the '<em><b>Def Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__DEF_COMMANDS = 1;

  /**
   * The feature id for the '<em><b>Def Output</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__DEF_OUTPUT = 2;

  /**
   * The number of structural features of the '<em>Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.InputImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getInput()
   * @generated
   */
  int INPUT = 3;

  /**
   * The feature id for the '<em><b>Vai</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__VAI = 0;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.OutputImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 4;

  /**
   * The feature id for the '<em><b>Vao</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__VAO = 0;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.CommandsImpl <em>Commands</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.CommandsImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getCommands()
   * @generated
   */
  int COMMANDS = 5;

  /**
   * The feature id for the '<em><b>LCommand</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDS__LCOMMAND = 0;

  /**
   * The number of structural features of the '<em>Commands</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.CommandImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 6;

  /**
   * The feature id for the '<em><b>Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__EQ = 0;

  /**
   * The feature id for the '<em><b>No</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__NO = 1;

  /**
   * The feature id for the '<em><b>If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__IF = 2;

  /**
   * The feature id for the '<em><b>Wh</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__WH = 3;

  /**
   * The feature id for the '<em><b>Fo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__FO = 4;

  /**
   * The feature id for the '<em><b>Fore</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__FORE = 5;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.EqualImpl <em>Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.EqualImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getEqual()
   * @generated
   */
  int EQUAL = 7;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__VARS = 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__EXP = 1;

  /**
   * The number of structural features of the '<em>Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.IfImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getIf()
   * @generated
   */
  int IF = 8;

  /**
   * The feature id for the '<em><b>Ifexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__IFEXP = 0;

  /**
   * The feature id for the '<em><b>Iflc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__IFLC = 1;

  /**
   * The feature id for the '<em><b>Ellc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__ELLC = 2;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.WhileImpl <em>While</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.WhileImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getWhile()
   * @generated
   */
  int WHILE = 9;

  /**
   * The feature id for the '<em><b>Whexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__WHEXP = 0;

  /**
   * The feature id for the '<em><b>Whcom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__WHCOM = 1;

  /**
   * The number of structural features of the '<em>While</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.ForImpl <em>For</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.ForImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getFor()
   * @generated
   */
  int FOR = 10;

  /**
   * The feature id for the '<em><b>Foexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__FOEXP = 0;

  /**
   * The feature id for the '<em><b>Focom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__FOCOM = 1;

  /**
   * The number of structural features of the '<em>For</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.ForeachImpl <em>Foreach</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.ForeachImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getForeach()
   * @generated
   */
  int FOREACH = 11;

  /**
   * The feature id for the '<em><b>Forevar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOREACH__FOREVAR = 0;

  /**
   * The feature id for the '<em><b>Foreexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOREACH__FOREEXP = 1;

  /**
   * The feature id for the '<em><b>Forecom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOREACH__FORECOM = 2;

  /**
   * The number of structural features of the '<em>Foreach</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOREACH_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.VarsImpl <em>Vars</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.VarsImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getVars()
   * @generated
   */
  int VARS = 12;

  /**
   * The feature id for the '<em><b>Lvars</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARS__LVARS = 0;

  /**
   * The number of structural features of the '<em>Vars</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.ExprsImpl <em>Exprs</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.ExprsImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getExprs()
   * @generated
   */
  int EXPRS = 13;

  /**
   * The feature id for the '<em><b>Lexpr</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRS__LEXPR = 0;

  /**
   * The number of structural features of the '<em>Exprs</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.ExpressionImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 14;

  /**
   * The feature id for the '<em><b>Expbg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__EXPBG = 0;

  /**
   * The feature id for the '<em><b>Expbd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__EXPBD = 1;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.ExprBaseImpl <em>Expr Base</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.ExprBaseImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getExprBase()
   * @generated
   */
  int EXPR_BASE = 15;

  /**
   * The feature id for the '<em><b>Ni</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__NI = 0;

  /**
   * The feature id for the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__V = 1;

  /**
   * The feature id for the '<em><b>Sy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__SY = 2;

  /**
   * The feature id for the '<em><b>Ebt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__EBT = 3;

  /**
   * The feature id for the '<em><b>Ebh</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__EBH = 4;

  /**
   * The feature id for the '<em><b>Ebc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__EBC = 5;

  /**
   * The feature id for the '<em><b>Ebl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__EBL = 6;

  /**
   * The feature id for the '<em><b>Ebs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__EBS = 7;

  /**
   * The number of structural features of the '<em>Expr Base</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.EBsyImpl <em>EBsy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.EBsyImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getEBsy()
   * @generated
   */
  int EBSY = 16;

  /**
   * The feature id for the '<em><b>Sy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBSY__SY = 0;

  /**
   * The feature id for the '<em><b>Lexpb</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBSY__LEXPB = 1;

  /**
   * The number of structural features of the '<em>EBsy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBSY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.EBhdImpl <em>EBhd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.EBhdImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getEBhd()
   * @generated
   */
  int EBHD = 17;

  /**
   * The feature id for the '<em><b>Expb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBHD__EXPB = 0;

  /**
   * The number of structural features of the '<em>EBhd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBHD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.EBtlImpl <em>EBtl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.EBtlImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getEBtl()
   * @generated
   */
  int EBTL = 18;

  /**
   * The feature id for the '<em><b>Expb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBTL__EXPB = 0;

  /**
   * The number of structural features of the '<em>EBtl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBTL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.EBconsImpl <em>EBcons</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.EBconsImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getEBcons()
   * @generated
   */
  int EBCONS = 19;

  /**
   * The feature id for the '<em><b>Lexpb</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBCONS__LEXPB = 0;

  /**
   * The number of structural features of the '<em>EBcons</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBCONS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.EBlistImpl <em>EBlist</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.EBlistImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getEBlist()
   * @generated
   */
  int EBLIST = 20;

  /**
   * The feature id for the '<em><b>Lexpb</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBLIST__LEXPB = 0;

  /**
   * The number of structural features of the '<em>EBlist</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBLIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pret.myDsl.impl.LExprImpl <em>LExpr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pret.myDsl.impl.LExprImpl
   * @see pret.myDsl.impl.MyDslPackageImpl#getLExpr()
   * @generated
   */
  int LEXPR = 21;

  /**
   * The feature id for the '<em><b>Lexpb</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEXPR__LEXPB = 0;

  /**
   * The number of structural features of the '<em>LExpr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEXPR_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link pret.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see pret.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link pret.myDsl.Model#getFunc <em>Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Func</em>'.
   * @see pret.myDsl.Model#getFunc()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Func();

  /**
   * Returns the meta object for class '{@link pret.myDsl.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see pret.myDsl.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link pret.myDsl.Function#getFname <em>Fname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fname</em>'.
   * @see pret.myDsl.Function#getFname()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Fname();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Function#getFdef <em>Fdef</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fdef</em>'.
   * @see pret.myDsl.Function#getFdef()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Fdef();

  /**
   * Returns the meta object for class '{@link pret.myDsl.Definition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Definition</em>'.
   * @see pret.myDsl.Definition
   * @generated
   */
  EClass getDefinition();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Definition#getDefInput <em>Def Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Def Input</em>'.
   * @see pret.myDsl.Definition#getDefInput()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_DefInput();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Definition#getDefCommands <em>Def Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Def Commands</em>'.
   * @see pret.myDsl.Definition#getDefCommands()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_DefCommands();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Definition#getDefOutput <em>Def Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Def Output</em>'.
   * @see pret.myDsl.Definition#getDefOutput()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_DefOutput();

  /**
   * Returns the meta object for class '{@link pret.myDsl.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see pret.myDsl.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for the attribute list '{@link pret.myDsl.Input#getVai <em>Vai</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Vai</em>'.
   * @see pret.myDsl.Input#getVai()
   * @see #getInput()
   * @generated
   */
  EAttribute getInput_Vai();

  /**
   * Returns the meta object for class '{@link pret.myDsl.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see pret.myDsl.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the attribute list '{@link pret.myDsl.Output#getVao <em>Vao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Vao</em>'.
   * @see pret.myDsl.Output#getVao()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Vao();

  /**
   * Returns the meta object for class '{@link pret.myDsl.Commands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Commands</em>'.
   * @see pret.myDsl.Commands
   * @generated
   */
  EClass getCommands();

  /**
   * Returns the meta object for the containment reference list '{@link pret.myDsl.Commands#getLCommand <em>LCommand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>LCommand</em>'.
   * @see pret.myDsl.Commands#getLCommand()
   * @see #getCommands()
   * @generated
   */
  EReference getCommands_LCommand();

  /**
   * Returns the meta object for class '{@link pret.myDsl.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see pret.myDsl.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Command#getEq <em>Eq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Eq</em>'.
   * @see pret.myDsl.Command#getEq()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Eq();

  /**
   * Returns the meta object for the attribute '{@link pret.myDsl.Command#getNo <em>No</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>No</em>'.
   * @see pret.myDsl.Command#getNo()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_No();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Command#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>If</em>'.
   * @see pret.myDsl.Command#getIf()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_If();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Command#getWh <em>Wh</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Wh</em>'.
   * @see pret.myDsl.Command#getWh()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Wh();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Command#getFo <em>Fo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fo</em>'.
   * @see pret.myDsl.Command#getFo()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Fo();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Command#getFore <em>Fore</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fore</em>'.
   * @see pret.myDsl.Command#getFore()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Fore();

  /**
   * Returns the meta object for class '{@link pret.myDsl.Equal <em>Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equal</em>'.
   * @see pret.myDsl.Equal
   * @generated
   */
  EClass getEqual();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Equal#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vars</em>'.
   * @see pret.myDsl.Equal#getVars()
   * @see #getEqual()
   * @generated
   */
  EReference getEqual_Vars();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Equal#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see pret.myDsl.Equal#getExp()
   * @see #getEqual()
   * @generated
   */
  EReference getEqual_Exp();

  /**
   * Returns the meta object for class '{@link pret.myDsl.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see pret.myDsl.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.If#getIfexp <em>Ifexp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ifexp</em>'.
   * @see pret.myDsl.If#getIfexp()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Ifexp();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.If#getIflc <em>Iflc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Iflc</em>'.
   * @see pret.myDsl.If#getIflc()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Iflc();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.If#getEllc <em>Ellc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ellc</em>'.
   * @see pret.myDsl.If#getEllc()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Ellc();

  /**
   * Returns the meta object for class '{@link pret.myDsl.While <em>While</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While</em>'.
   * @see pret.myDsl.While
   * @generated
   */
  EClass getWhile();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.While#getWhexp <em>Whexp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Whexp</em>'.
   * @see pret.myDsl.While#getWhexp()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Whexp();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.While#getWhcom <em>Whcom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Whcom</em>'.
   * @see pret.myDsl.While#getWhcom()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Whcom();

  /**
   * Returns the meta object for class '{@link pret.myDsl.For <em>For</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For</em>'.
   * @see pret.myDsl.For
   * @generated
   */
  EClass getFor();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.For#getFoexp <em>Foexp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Foexp</em>'.
   * @see pret.myDsl.For#getFoexp()
   * @see #getFor()
   * @generated
   */
  EReference getFor_Foexp();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.For#getFocom <em>Focom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Focom</em>'.
   * @see pret.myDsl.For#getFocom()
   * @see #getFor()
   * @generated
   */
  EReference getFor_Focom();

  /**
   * Returns the meta object for class '{@link pret.myDsl.Foreach <em>Foreach</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Foreach</em>'.
   * @see pret.myDsl.Foreach
   * @generated
   */
  EClass getForeach();

  /**
   * Returns the meta object for the attribute '{@link pret.myDsl.Foreach#getForevar <em>Forevar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Forevar</em>'.
   * @see pret.myDsl.Foreach#getForevar()
   * @see #getForeach()
   * @generated
   */
  EAttribute getForeach_Forevar();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Foreach#getForeexp <em>Foreexp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Foreexp</em>'.
   * @see pret.myDsl.Foreach#getForeexp()
   * @see #getForeach()
   * @generated
   */
  EReference getForeach_Foreexp();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Foreach#getForecom <em>Forecom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Forecom</em>'.
   * @see pret.myDsl.Foreach#getForecom()
   * @see #getForeach()
   * @generated
   */
  EReference getForeach_Forecom();

  /**
   * Returns the meta object for class '{@link pret.myDsl.Vars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vars</em>'.
   * @see pret.myDsl.Vars
   * @generated
   */
  EClass getVars();

  /**
   * Returns the meta object for the attribute list '{@link pret.myDsl.Vars#getLvars <em>Lvars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Lvars</em>'.
   * @see pret.myDsl.Vars#getLvars()
   * @see #getVars()
   * @generated
   */
  EAttribute getVars_Lvars();

  /**
   * Returns the meta object for class '{@link pret.myDsl.Exprs <em>Exprs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exprs</em>'.
   * @see pret.myDsl.Exprs
   * @generated
   */
  EClass getExprs();

  /**
   * Returns the meta object for the containment reference list '{@link pret.myDsl.Exprs#getLexpr <em>Lexpr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lexpr</em>'.
   * @see pret.myDsl.Exprs#getLexpr()
   * @see #getExprs()
   * @generated
   */
  EReference getExprs_Lexpr();

  /**
   * Returns the meta object for class '{@link pret.myDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see pret.myDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Expression#getExpbg <em>Expbg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expbg</em>'.
   * @see pret.myDsl.Expression#getExpbg()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Expbg();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.Expression#getExpbd <em>Expbd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expbd</em>'.
   * @see pret.myDsl.Expression#getExpbd()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Expbd();

  /**
   * Returns the meta object for class '{@link pret.myDsl.ExprBase <em>Expr Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Base</em>'.
   * @see pret.myDsl.ExprBase
   * @generated
   */
  EClass getExprBase();

  /**
   * Returns the meta object for the attribute '{@link pret.myDsl.ExprBase#getNi <em>Ni</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ni</em>'.
   * @see pret.myDsl.ExprBase#getNi()
   * @see #getExprBase()
   * @generated
   */
  EAttribute getExprBase_Ni();

  /**
   * Returns the meta object for the attribute '{@link pret.myDsl.ExprBase#getV <em>V</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>V</em>'.
   * @see pret.myDsl.ExprBase#getV()
   * @see #getExprBase()
   * @generated
   */
  EAttribute getExprBase_V();

  /**
   * Returns the meta object for the attribute '{@link pret.myDsl.ExprBase#getSy <em>Sy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sy</em>'.
   * @see pret.myDsl.ExprBase#getSy()
   * @see #getExprBase()
   * @generated
   */
  EAttribute getExprBase_Sy();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.ExprBase#getEbt <em>Ebt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ebt</em>'.
   * @see pret.myDsl.ExprBase#getEbt()
   * @see #getExprBase()
   * @generated
   */
  EReference getExprBase_Ebt();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.ExprBase#getEbh <em>Ebh</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ebh</em>'.
   * @see pret.myDsl.ExprBase#getEbh()
   * @see #getExprBase()
   * @generated
   */
  EReference getExprBase_Ebh();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.ExprBase#getEbc <em>Ebc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ebc</em>'.
   * @see pret.myDsl.ExprBase#getEbc()
   * @see #getExprBase()
   * @generated
   */
  EReference getExprBase_Ebc();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.ExprBase#getEbl <em>Ebl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ebl</em>'.
   * @see pret.myDsl.ExprBase#getEbl()
   * @see #getExprBase()
   * @generated
   */
  EReference getExprBase_Ebl();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.ExprBase#getEbs <em>Ebs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ebs</em>'.
   * @see pret.myDsl.ExprBase#getEbs()
   * @see #getExprBase()
   * @generated
   */
  EReference getExprBase_Ebs();

  /**
   * Returns the meta object for class '{@link pret.myDsl.EBsy <em>EBsy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EBsy</em>'.
   * @see pret.myDsl.EBsy
   * @generated
   */
  EClass getEBsy();

  /**
   * Returns the meta object for the attribute '{@link pret.myDsl.EBsy#getSy <em>Sy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sy</em>'.
   * @see pret.myDsl.EBsy#getSy()
   * @see #getEBsy()
   * @generated
   */
  EAttribute getEBsy_Sy();

  /**
   * Returns the meta object for the containment reference list '{@link pret.myDsl.EBsy#getLexpb <em>Lexpb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lexpb</em>'.
   * @see pret.myDsl.EBsy#getLexpb()
   * @see #getEBsy()
   * @generated
   */
  EReference getEBsy_Lexpb();

  /**
   * Returns the meta object for class '{@link pret.myDsl.EBhd <em>EBhd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EBhd</em>'.
   * @see pret.myDsl.EBhd
   * @generated
   */
  EClass getEBhd();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.EBhd#getExpb <em>Expb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expb</em>'.
   * @see pret.myDsl.EBhd#getExpb()
   * @see #getEBhd()
   * @generated
   */
  EReference getEBhd_Expb();

  /**
   * Returns the meta object for class '{@link pret.myDsl.EBtl <em>EBtl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EBtl</em>'.
   * @see pret.myDsl.EBtl
   * @generated
   */
  EClass getEBtl();

  /**
   * Returns the meta object for the containment reference '{@link pret.myDsl.EBtl#getExpb <em>Expb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expb</em>'.
   * @see pret.myDsl.EBtl#getExpb()
   * @see #getEBtl()
   * @generated
   */
  EReference getEBtl_Expb();

  /**
   * Returns the meta object for class '{@link pret.myDsl.EBcons <em>EBcons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EBcons</em>'.
   * @see pret.myDsl.EBcons
   * @generated
   */
  EClass getEBcons();

  /**
   * Returns the meta object for the containment reference list '{@link pret.myDsl.EBcons#getLexpb <em>Lexpb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lexpb</em>'.
   * @see pret.myDsl.EBcons#getLexpb()
   * @see #getEBcons()
   * @generated
   */
  EReference getEBcons_Lexpb();

  /**
   * Returns the meta object for class '{@link pret.myDsl.EBlist <em>EBlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EBlist</em>'.
   * @see pret.myDsl.EBlist
   * @generated
   */
  EClass getEBlist();

  /**
   * Returns the meta object for the containment reference list '{@link pret.myDsl.EBlist#getLexpb <em>Lexpb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lexpb</em>'.
   * @see pret.myDsl.EBlist#getLexpb()
   * @see #getEBlist()
   * @generated
   */
  EReference getEBlist_Lexpb();

  /**
   * Returns the meta object for class '{@link pret.myDsl.LExpr <em>LExpr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LExpr</em>'.
   * @see pret.myDsl.LExpr
   * @generated
   */
  EClass getLExpr();

  /**
   * Returns the meta object for the containment reference list '{@link pret.myDsl.LExpr#getLexpb <em>Lexpb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lexpb</em>'.
   * @see pret.myDsl.LExpr#getLexpb()
   * @see #getLExpr()
   * @generated
   */
  EReference getLExpr_Lexpb();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link pret.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.ModelImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Func</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__FUNC = eINSTANCE.getModel_Func();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.FunctionImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Fname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__FNAME = eINSTANCE.getFunction_Fname();

    /**
     * The meta object literal for the '<em><b>Fdef</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__FDEF = eINSTANCE.getFunction_Fdef();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.DefinitionImpl <em>Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.DefinitionImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getDefinition()
     * @generated
     */
    EClass DEFINITION = eINSTANCE.getDefinition();

    /**
     * The meta object literal for the '<em><b>Def Input</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__DEF_INPUT = eINSTANCE.getDefinition_DefInput();

    /**
     * The meta object literal for the '<em><b>Def Commands</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__DEF_COMMANDS = eINSTANCE.getDefinition_DefCommands();

    /**
     * The meta object literal for the '<em><b>Def Output</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__DEF_OUTPUT = eINSTANCE.getDefinition_DefOutput();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.InputImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '<em><b>Vai</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT__VAI = eINSTANCE.getInput_Vai();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.OutputImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Vao</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__VAO = eINSTANCE.getOutput_Vao();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.CommandsImpl <em>Commands</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.CommandsImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getCommands()
     * @generated
     */
    EClass COMMANDS = eINSTANCE.getCommands();

    /**
     * The meta object literal for the '<em><b>LCommand</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMANDS__LCOMMAND = eINSTANCE.getCommands_LCommand();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.CommandImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Eq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__EQ = eINSTANCE.getCommand_Eq();

    /**
     * The meta object literal for the '<em><b>No</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__NO = eINSTANCE.getCommand_No();

    /**
     * The meta object literal for the '<em><b>If</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__IF = eINSTANCE.getCommand_If();

    /**
     * The meta object literal for the '<em><b>Wh</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__WH = eINSTANCE.getCommand_Wh();

    /**
     * The meta object literal for the '<em><b>Fo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__FO = eINSTANCE.getCommand_Fo();

    /**
     * The meta object literal for the '<em><b>Fore</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__FORE = eINSTANCE.getCommand_Fore();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.EqualImpl <em>Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.EqualImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getEqual()
     * @generated
     */
    EClass EQUAL = eINSTANCE.getEqual();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUAL__VARS = eINSTANCE.getEqual_Vars();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUAL__EXP = eINSTANCE.getEqual_Exp();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.IfImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '<em><b>Ifexp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__IFEXP = eINSTANCE.getIf_Ifexp();

    /**
     * The meta object literal for the '<em><b>Iflc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__IFLC = eINSTANCE.getIf_Iflc();

    /**
     * The meta object literal for the '<em><b>Ellc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__ELLC = eINSTANCE.getIf_Ellc();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.WhileImpl <em>While</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.WhileImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getWhile()
     * @generated
     */
    EClass WHILE = eINSTANCE.getWhile();

    /**
     * The meta object literal for the '<em><b>Whexp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__WHEXP = eINSTANCE.getWhile_Whexp();

    /**
     * The meta object literal for the '<em><b>Whcom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__WHCOM = eINSTANCE.getWhile_Whcom();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.ForImpl <em>For</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.ForImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getFor()
     * @generated
     */
    EClass FOR = eINSTANCE.getFor();

    /**
     * The meta object literal for the '<em><b>Foexp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__FOEXP = eINSTANCE.getFor_Foexp();

    /**
     * The meta object literal for the '<em><b>Focom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__FOCOM = eINSTANCE.getFor_Focom();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.ForeachImpl <em>Foreach</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.ForeachImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getForeach()
     * @generated
     */
    EClass FOREACH = eINSTANCE.getForeach();

    /**
     * The meta object literal for the '<em><b>Forevar</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOREACH__FOREVAR = eINSTANCE.getForeach_Forevar();

    /**
     * The meta object literal for the '<em><b>Foreexp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOREACH__FOREEXP = eINSTANCE.getForeach_Foreexp();

    /**
     * The meta object literal for the '<em><b>Forecom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOREACH__FORECOM = eINSTANCE.getForeach_Forecom();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.VarsImpl <em>Vars</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.VarsImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getVars()
     * @generated
     */
    EClass VARS = eINSTANCE.getVars();

    /**
     * The meta object literal for the '<em><b>Lvars</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARS__LVARS = eINSTANCE.getVars_Lvars();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.ExprsImpl <em>Exprs</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.ExprsImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getExprs()
     * @generated
     */
    EClass EXPRS = eINSTANCE.getExprs();

    /**
     * The meta object literal for the '<em><b>Lexpr</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRS__LEXPR = eINSTANCE.getExprs_Lexpr();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.ExpressionImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Expbg</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__EXPBG = eINSTANCE.getExpression_Expbg();

    /**
     * The meta object literal for the '<em><b>Expbd</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__EXPBD = eINSTANCE.getExpression_Expbd();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.ExprBaseImpl <em>Expr Base</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.ExprBaseImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getExprBase()
     * @generated
     */
    EClass EXPR_BASE = eINSTANCE.getExprBase();

    /**
     * The meta object literal for the '<em><b>Ni</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_BASE__NI = eINSTANCE.getExprBase_Ni();

    /**
     * The meta object literal for the '<em><b>V</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_BASE__V = eINSTANCE.getExprBase_V();

    /**
     * The meta object literal for the '<em><b>Sy</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_BASE__SY = eINSTANCE.getExprBase_Sy();

    /**
     * The meta object literal for the '<em><b>Ebt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_BASE__EBT = eINSTANCE.getExprBase_Ebt();

    /**
     * The meta object literal for the '<em><b>Ebh</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_BASE__EBH = eINSTANCE.getExprBase_Ebh();

    /**
     * The meta object literal for the '<em><b>Ebc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_BASE__EBC = eINSTANCE.getExprBase_Ebc();

    /**
     * The meta object literal for the '<em><b>Ebl</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_BASE__EBL = eINSTANCE.getExprBase_Ebl();

    /**
     * The meta object literal for the '<em><b>Ebs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_BASE__EBS = eINSTANCE.getExprBase_Ebs();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.EBsyImpl <em>EBsy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.EBsyImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getEBsy()
     * @generated
     */
    EClass EBSY = eINSTANCE.getEBsy();

    /**
     * The meta object literal for the '<em><b>Sy</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EBSY__SY = eINSTANCE.getEBsy_Sy();

    /**
     * The meta object literal for the '<em><b>Lexpb</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EBSY__LEXPB = eINSTANCE.getEBsy_Lexpb();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.EBhdImpl <em>EBhd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.EBhdImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getEBhd()
     * @generated
     */
    EClass EBHD = eINSTANCE.getEBhd();

    /**
     * The meta object literal for the '<em><b>Expb</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EBHD__EXPB = eINSTANCE.getEBhd_Expb();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.EBtlImpl <em>EBtl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.EBtlImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getEBtl()
     * @generated
     */
    EClass EBTL = eINSTANCE.getEBtl();

    /**
     * The meta object literal for the '<em><b>Expb</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EBTL__EXPB = eINSTANCE.getEBtl_Expb();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.EBconsImpl <em>EBcons</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.EBconsImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getEBcons()
     * @generated
     */
    EClass EBCONS = eINSTANCE.getEBcons();

    /**
     * The meta object literal for the '<em><b>Lexpb</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EBCONS__LEXPB = eINSTANCE.getEBcons_Lexpb();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.EBlistImpl <em>EBlist</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.EBlistImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getEBlist()
     * @generated
     */
    EClass EBLIST = eINSTANCE.getEBlist();

    /**
     * The meta object literal for the '<em><b>Lexpb</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EBLIST__LEXPB = eINSTANCE.getEBlist_Lexpb();

    /**
     * The meta object literal for the '{@link pret.myDsl.impl.LExprImpl <em>LExpr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pret.myDsl.impl.LExprImpl
     * @see pret.myDsl.impl.MyDslPackageImpl#getLExpr()
     * @generated
     */
    EClass LEXPR = eINSTANCE.getLExpr();

    /**
     * The meta object literal for the '<em><b>Lexpb</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEXPR__LEXPB = eINSTANCE.getLExpr_Lexpb();

  }

} //MyDslPackage
