/**
 * generated by Xtext 2.25.0
 */
package paramInterpreter.inter.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import paramInterpreter.inter.myDsl.EBcons;
import paramInterpreter.inter.myDsl.EBhd;
import paramInterpreter.inter.myDsl.EBlist;
import paramInterpreter.inter.myDsl.EBsy;
import paramInterpreter.inter.myDsl.EBtl;
import paramInterpreter.inter.myDsl.ExprBase;
import paramInterpreter.inter.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expr Base</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link paramInterpreter.inter.myDsl.impl.ExprBaseImpl#getNi <em>Ni</em>}</li>
 *   <li>{@link paramInterpreter.inter.myDsl.impl.ExprBaseImpl#getV <em>V</em>}</li>
 *   <li>{@link paramInterpreter.inter.myDsl.impl.ExprBaseImpl#getSy <em>Sy</em>}</li>
 *   <li>{@link paramInterpreter.inter.myDsl.impl.ExprBaseImpl#getEbt <em>Ebt</em>}</li>
 *   <li>{@link paramInterpreter.inter.myDsl.impl.ExprBaseImpl#getEbh <em>Ebh</em>}</li>
 *   <li>{@link paramInterpreter.inter.myDsl.impl.ExprBaseImpl#getEbc <em>Ebc</em>}</li>
 *   <li>{@link paramInterpreter.inter.myDsl.impl.ExprBaseImpl#getEbl <em>Ebl</em>}</li>
 *   <li>{@link paramInterpreter.inter.myDsl.impl.ExprBaseImpl#getEbs <em>Ebs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExprBaseImpl extends MinimalEObjectImpl.Container implements ExprBase
{
  /**
   * The default value of the '{@link #getNi() <em>Ni</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNi()
   * @generated
   * @ordered
   */
  protected static final String NI_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNi() <em>Ni</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNi()
   * @generated
   * @ordered
   */
  protected String ni = NI_EDEFAULT;

  /**
   * The default value of the '{@link #getV() <em>V</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getV()
   * @generated
   * @ordered
   */
  protected static final String V_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getV() <em>V</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getV()
   * @generated
   * @ordered
   */
  protected String v = V_EDEFAULT;

  /**
   * The default value of the '{@link #getSy() <em>Sy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSy()
   * @generated
   * @ordered
   */
  protected static final String SY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSy() <em>Sy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSy()
   * @generated
   * @ordered
   */
  protected String sy = SY_EDEFAULT;

  /**
   * The cached value of the '{@link #getEbt() <em>Ebt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEbt()
   * @generated
   * @ordered
   */
  protected EBtl ebt;

  /**
   * The cached value of the '{@link #getEbh() <em>Ebh</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEbh()
   * @generated
   * @ordered
   */
  protected EBhd ebh;

  /**
   * The cached value of the '{@link #getEbc() <em>Ebc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEbc()
   * @generated
   * @ordered
   */
  protected EBcons ebc;

  /**
   * The cached value of the '{@link #getEbl() <em>Ebl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEbl()
   * @generated
   * @ordered
   */
  protected EBlist ebl;

  /**
   * The cached value of the '{@link #getEbs() <em>Ebs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEbs()
   * @generated
   * @ordered
   */
  protected EBsy ebs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExprBaseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EXPR_BASE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNi()
  {
    return ni;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNi(String newNi)
  {
    String oldNi = ni;
    ni = newNi;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__NI, oldNi, ni));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getV()
  {
    return v;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setV(String newV)
  {
    String oldV = v;
    v = newV;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__V, oldV, v));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSy()
  {
    return sy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSy(String newSy)
  {
    String oldSy = sy;
    sy = newSy;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__SY, oldSy, sy));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EBtl getEbt()
  {
    return ebt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEbt(EBtl newEbt, NotificationChain msgs)
  {
    EBtl oldEbt = ebt;
    ebt = newEbt;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__EBT, oldEbt, newEbt);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEbt(EBtl newEbt)
  {
    if (newEbt != ebt)
    {
      NotificationChain msgs = null;
      if (ebt != null)
        msgs = ((InternalEObject)ebt).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR_BASE__EBT, null, msgs);
      if (newEbt != null)
        msgs = ((InternalEObject)newEbt).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR_BASE__EBT, null, msgs);
      msgs = basicSetEbt(newEbt, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__EBT, newEbt, newEbt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EBhd getEbh()
  {
    return ebh;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEbh(EBhd newEbh, NotificationChain msgs)
  {
    EBhd oldEbh = ebh;
    ebh = newEbh;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__EBH, oldEbh, newEbh);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEbh(EBhd newEbh)
  {
    if (newEbh != ebh)
    {
      NotificationChain msgs = null;
      if (ebh != null)
        msgs = ((InternalEObject)ebh).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR_BASE__EBH, null, msgs);
      if (newEbh != null)
        msgs = ((InternalEObject)newEbh).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR_BASE__EBH, null, msgs);
      msgs = basicSetEbh(newEbh, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__EBH, newEbh, newEbh));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EBcons getEbc()
  {
    return ebc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEbc(EBcons newEbc, NotificationChain msgs)
  {
    EBcons oldEbc = ebc;
    ebc = newEbc;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__EBC, oldEbc, newEbc);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEbc(EBcons newEbc)
  {
    if (newEbc != ebc)
    {
      NotificationChain msgs = null;
      if (ebc != null)
        msgs = ((InternalEObject)ebc).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR_BASE__EBC, null, msgs);
      if (newEbc != null)
        msgs = ((InternalEObject)newEbc).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR_BASE__EBC, null, msgs);
      msgs = basicSetEbc(newEbc, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__EBC, newEbc, newEbc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EBlist getEbl()
  {
    return ebl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEbl(EBlist newEbl, NotificationChain msgs)
  {
    EBlist oldEbl = ebl;
    ebl = newEbl;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__EBL, oldEbl, newEbl);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEbl(EBlist newEbl)
  {
    if (newEbl != ebl)
    {
      NotificationChain msgs = null;
      if (ebl != null)
        msgs = ((InternalEObject)ebl).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR_BASE__EBL, null, msgs);
      if (newEbl != null)
        msgs = ((InternalEObject)newEbl).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR_BASE__EBL, null, msgs);
      msgs = basicSetEbl(newEbl, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__EBL, newEbl, newEbl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EBsy getEbs()
  {
    return ebs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEbs(EBsy newEbs, NotificationChain msgs)
  {
    EBsy oldEbs = ebs;
    ebs = newEbs;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__EBS, oldEbs, newEbs);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEbs(EBsy newEbs)
  {
    if (newEbs != ebs)
    {
      NotificationChain msgs = null;
      if (ebs != null)
        msgs = ((InternalEObject)ebs).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR_BASE__EBS, null, msgs);
      if (newEbs != null)
        msgs = ((InternalEObject)newEbs).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXPR_BASE__EBS, null, msgs);
      msgs = basicSetEbs(newEbs, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXPR_BASE__EBS, newEbs, newEbs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.EXPR_BASE__EBT:
        return basicSetEbt(null, msgs);
      case MyDslPackage.EXPR_BASE__EBH:
        return basicSetEbh(null, msgs);
      case MyDslPackage.EXPR_BASE__EBC:
        return basicSetEbc(null, msgs);
      case MyDslPackage.EXPR_BASE__EBL:
        return basicSetEbl(null, msgs);
      case MyDslPackage.EXPR_BASE__EBS:
        return basicSetEbs(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.EXPR_BASE__NI:
        return getNi();
      case MyDslPackage.EXPR_BASE__V:
        return getV();
      case MyDslPackage.EXPR_BASE__SY:
        return getSy();
      case MyDslPackage.EXPR_BASE__EBT:
        return getEbt();
      case MyDslPackage.EXPR_BASE__EBH:
        return getEbh();
      case MyDslPackage.EXPR_BASE__EBC:
        return getEbc();
      case MyDslPackage.EXPR_BASE__EBL:
        return getEbl();
      case MyDslPackage.EXPR_BASE__EBS:
        return getEbs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.EXPR_BASE__NI:
        setNi((String)newValue);
        return;
      case MyDslPackage.EXPR_BASE__V:
        setV((String)newValue);
        return;
      case MyDslPackage.EXPR_BASE__SY:
        setSy((String)newValue);
        return;
      case MyDslPackage.EXPR_BASE__EBT:
        setEbt((EBtl)newValue);
        return;
      case MyDslPackage.EXPR_BASE__EBH:
        setEbh((EBhd)newValue);
        return;
      case MyDslPackage.EXPR_BASE__EBC:
        setEbc((EBcons)newValue);
        return;
      case MyDslPackage.EXPR_BASE__EBL:
        setEbl((EBlist)newValue);
        return;
      case MyDslPackage.EXPR_BASE__EBS:
        setEbs((EBsy)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXPR_BASE__NI:
        setNi(NI_EDEFAULT);
        return;
      case MyDslPackage.EXPR_BASE__V:
        setV(V_EDEFAULT);
        return;
      case MyDslPackage.EXPR_BASE__SY:
        setSy(SY_EDEFAULT);
        return;
      case MyDslPackage.EXPR_BASE__EBT:
        setEbt((EBtl)null);
        return;
      case MyDslPackage.EXPR_BASE__EBH:
        setEbh((EBhd)null);
        return;
      case MyDslPackage.EXPR_BASE__EBC:
        setEbc((EBcons)null);
        return;
      case MyDslPackage.EXPR_BASE__EBL:
        setEbl((EBlist)null);
        return;
      case MyDslPackage.EXPR_BASE__EBS:
        setEbs((EBsy)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXPR_BASE__NI:
        return NI_EDEFAULT == null ? ni != null : !NI_EDEFAULT.equals(ni);
      case MyDslPackage.EXPR_BASE__V:
        return V_EDEFAULT == null ? v != null : !V_EDEFAULT.equals(v);
      case MyDslPackage.EXPR_BASE__SY:
        return SY_EDEFAULT == null ? sy != null : !SY_EDEFAULT.equals(sy);
      case MyDslPackage.EXPR_BASE__EBT:
        return ebt != null;
      case MyDslPackage.EXPR_BASE__EBH:
        return ebh != null;
      case MyDslPackage.EXPR_BASE__EBC:
        return ebc != null;
      case MyDslPackage.EXPR_BASE__EBL:
        return ebl != null;
      case MyDslPackage.EXPR_BASE__EBS:
        return ebs != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ni: ");
    result.append(ni);
    result.append(", v: ");
    result.append(v);
    result.append(", sy: ");
    result.append(sy);
    result.append(')');
    return result.toString();
  }

} //ExprBaseImpl
