/**
 * generated by Xtext 2.25.0
 */
package paramInterpreter.inter.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EBsy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link paramInterpreter.inter.myDsl.EBsy#getSy <em>Sy</em>}</li>
 *   <li>{@link paramInterpreter.inter.myDsl.EBsy#getLexpb <em>Lexpb</em>}</li>
 * </ul>
 *
 * @see paramInterpreter.inter.myDsl.MyDslPackage#getEBsy()
 * @model
 * @generated
 */
public interface EBsy extends EObject
{
  /**
   * Returns the value of the '<em><b>Sy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sy</em>' attribute.
   * @see #setSy(String)
   * @see paramInterpreter.inter.myDsl.MyDslPackage#getEBsy_Sy()
   * @model
   * @generated
   */
  String getSy();

  /**
   * Sets the value of the '{@link paramInterpreter.inter.myDsl.EBsy#getSy <em>Sy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sy</em>' attribute.
   * @see #getSy()
   * @generated
   */
  void setSy(String value);

  /**
   * Returns the value of the '<em><b>Lexpb</b></em>' containment reference list.
   * The list contents are of type {@link paramInterpreter.inter.myDsl.ExprBase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lexpb</em>' containment reference list.
   * @see paramInterpreter.inter.myDsl.MyDslPackage#getEBsy_Lexpb()
   * @model containment="true"
   * @generated
   */
  EList<ExprBase> getLexpb();

} // EBsy
