/**
 * generated by Xtext 2.25.0
 */
package paramInterpreter.inter.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exprs</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link paramInterpreter.inter.myDsl.Exprs#getLexpr <em>Lexpr</em>}</li>
 * </ul>
 *
 * @see paramInterpreter.inter.myDsl.MyDslPackage#getExprs()
 * @model
 * @generated
 */
public interface Exprs extends EObject
{
  /**
   * Returns the value of the '<em><b>Lexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lexpr</em>' containment reference.
   * @see #setLexpr(Expression)
   * @see paramInterpreter.inter.myDsl.MyDslPackage#getExprs_Lexpr()
   * @model containment="true"
   * @generated
   */
  Expression getLexpr();

  /**
   * Sets the value of the '{@link paramInterpreter.inter.myDsl.Exprs#getLexpr <em>Lexpr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lexpr</em>' containment reference.
   * @see #getLexpr()
   * @generated
   */
  void setLexpr(Expression value);

} // Exprs
