/**
 * generated by Xtext 2.25.0
 */
package paramInterpreter.inter.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link paramInterpreter.inter.myDsl.Model#getEqListe <em>Eq Liste</em>}</li>
 * </ul>
 *
 * @see paramInterpreter.inter.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Eq Liste</b></em>' containment reference list.
   * The list contents are of type {@link paramInterpreter.inter.myDsl.Equal}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eq Liste</em>' containment reference list.
   * @see paramInterpreter.inter.myDsl.MyDslPackage#getModel_EqListe()
   * @model containment="true"
   * @generated
   */
  EList<Equal> getEqListe();

} // Model
