/**
 * generated by Xtext 2.25.0
 */
package paramInterpreter.inter.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see paramInterpreter.inter.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.inter.paramInterpreter/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = paramInterpreter.inter.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link paramInterpreter.inter.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see paramInterpreter.inter.myDsl.impl.ModelImpl
   * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Eq Liste</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__EQ_LISTE = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link paramInterpreter.inter.myDsl.impl.EqualImpl <em>Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see paramInterpreter.inter.myDsl.impl.EqualImpl
   * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEqual()
   * @generated
   */
  int EQUAL = 1;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__VARS = 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__EXP = 1;

  /**
   * The number of structural features of the '<em>Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link paramInterpreter.inter.myDsl.impl.VarsImpl <em>Vars</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see paramInterpreter.inter.myDsl.impl.VarsImpl
   * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getVars()
   * @generated
   */
  int VARS = 2;

  /**
   * The feature id for the '<em><b>Lvars</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARS__LVARS = 0;

  /**
   * The number of structural features of the '<em>Vars</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link paramInterpreter.inter.myDsl.impl.ExprsImpl <em>Exprs</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see paramInterpreter.inter.myDsl.impl.ExprsImpl
   * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getExprs()
   * @generated
   */
  int EXPRS = 3;

  /**
   * The feature id for the '<em><b>Lexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRS__LEXPR = 0;

  /**
   * The number of structural features of the '<em>Exprs</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link paramInterpreter.inter.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see paramInterpreter.inter.myDsl.impl.ExpressionImpl
   * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 4;

  /**
   * The feature id for the '<em><b>Expbg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__EXPBG = 0;

  /**
   * The feature id for the '<em><b>Expbd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__EXPBD = 1;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link paramInterpreter.inter.myDsl.impl.ExprBaseImpl <em>Expr Base</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see paramInterpreter.inter.myDsl.impl.ExprBaseImpl
   * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getExprBase()
   * @generated
   */
  int EXPR_BASE = 5;

  /**
   * The feature id for the '<em><b>Ni</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__NI = 0;

  /**
   * The feature id for the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__V = 1;

  /**
   * The feature id for the '<em><b>Sy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__SY = 2;

  /**
   * The feature id for the '<em><b>Ebt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__EBT = 3;

  /**
   * The feature id for the '<em><b>Ebh</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__EBH = 4;

  /**
   * The feature id for the '<em><b>Ebc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__EBC = 5;

  /**
   * The feature id for the '<em><b>Ebl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__EBL = 6;

  /**
   * The feature id for the '<em><b>Ebs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE__EBS = 7;

  /**
   * The number of structural features of the '<em>Expr Base</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BASE_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link paramInterpreter.inter.myDsl.impl.EBsyImpl <em>EBsy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see paramInterpreter.inter.myDsl.impl.EBsyImpl
   * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEBsy()
   * @generated
   */
  int EBSY = 6;

  /**
   * The feature id for the '<em><b>Sy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBSY__SY = 0;

  /**
   * The feature id for the '<em><b>Lexpb</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBSY__LEXPB = 1;

  /**
   * The number of structural features of the '<em>EBsy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBSY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link paramInterpreter.inter.myDsl.impl.EBhdImpl <em>EBhd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see paramInterpreter.inter.myDsl.impl.EBhdImpl
   * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEBhd()
   * @generated
   */
  int EBHD = 7;

  /**
   * The feature id for the '<em><b>Expb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBHD__EXPB = 0;

  /**
   * The number of structural features of the '<em>EBhd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBHD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link paramInterpreter.inter.myDsl.impl.EBtlImpl <em>EBtl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see paramInterpreter.inter.myDsl.impl.EBtlImpl
   * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEBtl()
   * @generated
   */
  int EBTL = 8;

  /**
   * The feature id for the '<em><b>Expb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBTL__EXPB = 0;

  /**
   * The number of structural features of the '<em>EBtl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBTL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link paramInterpreter.inter.myDsl.impl.EBconsImpl <em>EBcons</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see paramInterpreter.inter.myDsl.impl.EBconsImpl
   * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEBcons()
   * @generated
   */
  int EBCONS = 9;

  /**
   * The feature id for the '<em><b>Lexpb</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBCONS__LEXPB = 0;

  /**
   * The number of structural features of the '<em>EBcons</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBCONS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link paramInterpreter.inter.myDsl.impl.EBlistImpl <em>EBlist</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see paramInterpreter.inter.myDsl.impl.EBlistImpl
   * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEBlist()
   * @generated
   */
  int EBLIST = 10;

  /**
   * The feature id for the '<em><b>Lexpb</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBLIST__LEXPB = 0;

  /**
   * The number of structural features of the '<em>EBlist</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBLIST_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link paramInterpreter.inter.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see paramInterpreter.inter.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link paramInterpreter.inter.myDsl.Model#getEqListe <em>Eq Liste</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Eq Liste</em>'.
   * @see paramInterpreter.inter.myDsl.Model#getEqListe()
   * @see #getModel()
   * @generated
   */
  EReference getModel_EqListe();

  /**
   * Returns the meta object for class '{@link paramInterpreter.inter.myDsl.Equal <em>Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equal</em>'.
   * @see paramInterpreter.inter.myDsl.Equal
   * @generated
   */
  EClass getEqual();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.Equal#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vars</em>'.
   * @see paramInterpreter.inter.myDsl.Equal#getVars()
   * @see #getEqual()
   * @generated
   */
  EReference getEqual_Vars();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.Equal#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see paramInterpreter.inter.myDsl.Equal#getExp()
   * @see #getEqual()
   * @generated
   */
  EReference getEqual_Exp();

  /**
   * Returns the meta object for class '{@link paramInterpreter.inter.myDsl.Vars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vars</em>'.
   * @see paramInterpreter.inter.myDsl.Vars
   * @generated
   */
  EClass getVars();

  /**
   * Returns the meta object for the attribute '{@link paramInterpreter.inter.myDsl.Vars#getLvars <em>Lvars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lvars</em>'.
   * @see paramInterpreter.inter.myDsl.Vars#getLvars()
   * @see #getVars()
   * @generated
   */
  EAttribute getVars_Lvars();

  /**
   * Returns the meta object for class '{@link paramInterpreter.inter.myDsl.Exprs <em>Exprs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exprs</em>'.
   * @see paramInterpreter.inter.myDsl.Exprs
   * @generated
   */
  EClass getExprs();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.Exprs#getLexpr <em>Lexpr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lexpr</em>'.
   * @see paramInterpreter.inter.myDsl.Exprs#getLexpr()
   * @see #getExprs()
   * @generated
   */
  EReference getExprs_Lexpr();

  /**
   * Returns the meta object for class '{@link paramInterpreter.inter.myDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see paramInterpreter.inter.myDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.Expression#getExpbg <em>Expbg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expbg</em>'.
   * @see paramInterpreter.inter.myDsl.Expression#getExpbg()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Expbg();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.Expression#getExpbd <em>Expbd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expbd</em>'.
   * @see paramInterpreter.inter.myDsl.Expression#getExpbd()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Expbd();

  /**
   * Returns the meta object for class '{@link paramInterpreter.inter.myDsl.ExprBase <em>Expr Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Base</em>'.
   * @see paramInterpreter.inter.myDsl.ExprBase
   * @generated
   */
  EClass getExprBase();

  /**
   * Returns the meta object for the attribute '{@link paramInterpreter.inter.myDsl.ExprBase#getNi <em>Ni</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ni</em>'.
   * @see paramInterpreter.inter.myDsl.ExprBase#getNi()
   * @see #getExprBase()
   * @generated
   */
  EAttribute getExprBase_Ni();

  /**
   * Returns the meta object for the attribute '{@link paramInterpreter.inter.myDsl.ExprBase#getV <em>V</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>V</em>'.
   * @see paramInterpreter.inter.myDsl.ExprBase#getV()
   * @see #getExprBase()
   * @generated
   */
  EAttribute getExprBase_V();

  /**
   * Returns the meta object for the attribute '{@link paramInterpreter.inter.myDsl.ExprBase#getSy <em>Sy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sy</em>'.
   * @see paramInterpreter.inter.myDsl.ExprBase#getSy()
   * @see #getExprBase()
   * @generated
   */
  EAttribute getExprBase_Sy();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.ExprBase#getEbt <em>Ebt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ebt</em>'.
   * @see paramInterpreter.inter.myDsl.ExprBase#getEbt()
   * @see #getExprBase()
   * @generated
   */
  EReference getExprBase_Ebt();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.ExprBase#getEbh <em>Ebh</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ebh</em>'.
   * @see paramInterpreter.inter.myDsl.ExprBase#getEbh()
   * @see #getExprBase()
   * @generated
   */
  EReference getExprBase_Ebh();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.ExprBase#getEbc <em>Ebc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ebc</em>'.
   * @see paramInterpreter.inter.myDsl.ExprBase#getEbc()
   * @see #getExprBase()
   * @generated
   */
  EReference getExprBase_Ebc();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.ExprBase#getEbl <em>Ebl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ebl</em>'.
   * @see paramInterpreter.inter.myDsl.ExprBase#getEbl()
   * @see #getExprBase()
   * @generated
   */
  EReference getExprBase_Ebl();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.ExprBase#getEbs <em>Ebs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ebs</em>'.
   * @see paramInterpreter.inter.myDsl.ExprBase#getEbs()
   * @see #getExprBase()
   * @generated
   */
  EReference getExprBase_Ebs();

  /**
   * Returns the meta object for class '{@link paramInterpreter.inter.myDsl.EBsy <em>EBsy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EBsy</em>'.
   * @see paramInterpreter.inter.myDsl.EBsy
   * @generated
   */
  EClass getEBsy();

  /**
   * Returns the meta object for the attribute '{@link paramInterpreter.inter.myDsl.EBsy#getSy <em>Sy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sy</em>'.
   * @see paramInterpreter.inter.myDsl.EBsy#getSy()
   * @see #getEBsy()
   * @generated
   */
  EAttribute getEBsy_Sy();

  /**
   * Returns the meta object for the containment reference list '{@link paramInterpreter.inter.myDsl.EBsy#getLexpb <em>Lexpb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lexpb</em>'.
   * @see paramInterpreter.inter.myDsl.EBsy#getLexpb()
   * @see #getEBsy()
   * @generated
   */
  EReference getEBsy_Lexpb();

  /**
   * Returns the meta object for class '{@link paramInterpreter.inter.myDsl.EBhd <em>EBhd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EBhd</em>'.
   * @see paramInterpreter.inter.myDsl.EBhd
   * @generated
   */
  EClass getEBhd();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.EBhd#getExpb <em>Expb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expb</em>'.
   * @see paramInterpreter.inter.myDsl.EBhd#getExpb()
   * @see #getEBhd()
   * @generated
   */
  EReference getEBhd_Expb();

  /**
   * Returns the meta object for class '{@link paramInterpreter.inter.myDsl.EBtl <em>EBtl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EBtl</em>'.
   * @see paramInterpreter.inter.myDsl.EBtl
   * @generated
   */
  EClass getEBtl();

  /**
   * Returns the meta object for the containment reference '{@link paramInterpreter.inter.myDsl.EBtl#getExpb <em>Expb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expb</em>'.
   * @see paramInterpreter.inter.myDsl.EBtl#getExpb()
   * @see #getEBtl()
   * @generated
   */
  EReference getEBtl_Expb();

  /**
   * Returns the meta object for class '{@link paramInterpreter.inter.myDsl.EBcons <em>EBcons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EBcons</em>'.
   * @see paramInterpreter.inter.myDsl.EBcons
   * @generated
   */
  EClass getEBcons();

  /**
   * Returns the meta object for the containment reference list '{@link paramInterpreter.inter.myDsl.EBcons#getLexpb <em>Lexpb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lexpb</em>'.
   * @see paramInterpreter.inter.myDsl.EBcons#getLexpb()
   * @see #getEBcons()
   * @generated
   */
  EReference getEBcons_Lexpb();

  /**
   * Returns the meta object for class '{@link paramInterpreter.inter.myDsl.EBlist <em>EBlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EBlist</em>'.
   * @see paramInterpreter.inter.myDsl.EBlist
   * @generated
   */
  EClass getEBlist();

  /**
   * Returns the meta object for the containment reference list '{@link paramInterpreter.inter.myDsl.EBlist#getLexpb <em>Lexpb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lexpb</em>'.
   * @see paramInterpreter.inter.myDsl.EBlist#getLexpb()
   * @see #getEBlist()
   * @generated
   */
  EReference getEBlist_Lexpb();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link paramInterpreter.inter.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see paramInterpreter.inter.myDsl.impl.ModelImpl
     * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Eq Liste</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__EQ_LISTE = eINSTANCE.getModel_EqListe();

    /**
     * The meta object literal for the '{@link paramInterpreter.inter.myDsl.impl.EqualImpl <em>Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see paramInterpreter.inter.myDsl.impl.EqualImpl
     * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEqual()
     * @generated
     */
    EClass EQUAL = eINSTANCE.getEqual();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUAL__VARS = eINSTANCE.getEqual_Vars();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUAL__EXP = eINSTANCE.getEqual_Exp();

    /**
     * The meta object literal for the '{@link paramInterpreter.inter.myDsl.impl.VarsImpl <em>Vars</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see paramInterpreter.inter.myDsl.impl.VarsImpl
     * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getVars()
     * @generated
     */
    EClass VARS = eINSTANCE.getVars();

    /**
     * The meta object literal for the '<em><b>Lvars</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARS__LVARS = eINSTANCE.getVars_Lvars();

    /**
     * The meta object literal for the '{@link paramInterpreter.inter.myDsl.impl.ExprsImpl <em>Exprs</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see paramInterpreter.inter.myDsl.impl.ExprsImpl
     * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getExprs()
     * @generated
     */
    EClass EXPRS = eINSTANCE.getExprs();

    /**
     * The meta object literal for the '<em><b>Lexpr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRS__LEXPR = eINSTANCE.getExprs_Lexpr();

    /**
     * The meta object literal for the '{@link paramInterpreter.inter.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see paramInterpreter.inter.myDsl.impl.ExpressionImpl
     * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Expbg</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__EXPBG = eINSTANCE.getExpression_Expbg();

    /**
     * The meta object literal for the '<em><b>Expbd</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__EXPBD = eINSTANCE.getExpression_Expbd();

    /**
     * The meta object literal for the '{@link paramInterpreter.inter.myDsl.impl.ExprBaseImpl <em>Expr Base</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see paramInterpreter.inter.myDsl.impl.ExprBaseImpl
     * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getExprBase()
     * @generated
     */
    EClass EXPR_BASE = eINSTANCE.getExprBase();

    /**
     * The meta object literal for the '<em><b>Ni</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_BASE__NI = eINSTANCE.getExprBase_Ni();

    /**
     * The meta object literal for the '<em><b>V</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_BASE__V = eINSTANCE.getExprBase_V();

    /**
     * The meta object literal for the '<em><b>Sy</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_BASE__SY = eINSTANCE.getExprBase_Sy();

    /**
     * The meta object literal for the '<em><b>Ebt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_BASE__EBT = eINSTANCE.getExprBase_Ebt();

    /**
     * The meta object literal for the '<em><b>Ebh</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_BASE__EBH = eINSTANCE.getExprBase_Ebh();

    /**
     * The meta object literal for the '<em><b>Ebc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_BASE__EBC = eINSTANCE.getExprBase_Ebc();

    /**
     * The meta object literal for the '<em><b>Ebl</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_BASE__EBL = eINSTANCE.getExprBase_Ebl();

    /**
     * The meta object literal for the '<em><b>Ebs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_BASE__EBS = eINSTANCE.getExprBase_Ebs();

    /**
     * The meta object literal for the '{@link paramInterpreter.inter.myDsl.impl.EBsyImpl <em>EBsy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see paramInterpreter.inter.myDsl.impl.EBsyImpl
     * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEBsy()
     * @generated
     */
    EClass EBSY = eINSTANCE.getEBsy();

    /**
     * The meta object literal for the '<em><b>Sy</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EBSY__SY = eINSTANCE.getEBsy_Sy();

    /**
     * The meta object literal for the '<em><b>Lexpb</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EBSY__LEXPB = eINSTANCE.getEBsy_Lexpb();

    /**
     * The meta object literal for the '{@link paramInterpreter.inter.myDsl.impl.EBhdImpl <em>EBhd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see paramInterpreter.inter.myDsl.impl.EBhdImpl
     * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEBhd()
     * @generated
     */
    EClass EBHD = eINSTANCE.getEBhd();

    /**
     * The meta object literal for the '<em><b>Expb</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EBHD__EXPB = eINSTANCE.getEBhd_Expb();

    /**
     * The meta object literal for the '{@link paramInterpreter.inter.myDsl.impl.EBtlImpl <em>EBtl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see paramInterpreter.inter.myDsl.impl.EBtlImpl
     * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEBtl()
     * @generated
     */
    EClass EBTL = eINSTANCE.getEBtl();

    /**
     * The meta object literal for the '<em><b>Expb</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EBTL__EXPB = eINSTANCE.getEBtl_Expb();

    /**
     * The meta object literal for the '{@link paramInterpreter.inter.myDsl.impl.EBconsImpl <em>EBcons</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see paramInterpreter.inter.myDsl.impl.EBconsImpl
     * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEBcons()
     * @generated
     */
    EClass EBCONS = eINSTANCE.getEBcons();

    /**
     * The meta object literal for the '<em><b>Lexpb</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EBCONS__LEXPB = eINSTANCE.getEBcons_Lexpb();

    /**
     * The meta object literal for the '{@link paramInterpreter.inter.myDsl.impl.EBlistImpl <em>EBlist</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see paramInterpreter.inter.myDsl.impl.EBlistImpl
     * @see paramInterpreter.inter.myDsl.impl.MyDslPackageImpl#getEBlist()
     * @generated
     */
    EClass EBLIST = eINSTANCE.getEBlist();

    /**
     * The meta object literal for the '<em><b>Lexpb</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EBLIST__LEXPB = eINSTANCE.getEBlist_Lexpb();

  }

} //MyDslPackage
