/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import pret.myDsl.Commands;
import pret.myDsl.Expression;
import pret.myDsl.For;
import pret.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>For</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link pret.myDsl.impl.ForImpl#getFoexp <em>Foexp</em>}</li>
 *   <li>{@link pret.myDsl.impl.ForImpl#getFocom <em>Focom</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ForImpl extends MinimalEObjectImpl.Container implements For
{
  /**
   * The cached value of the '{@link #getFoexp() <em>Foexp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFoexp()
   * @generated
   * @ordered
   */
  protected Expression foexp;

  /**
   * The cached value of the '{@link #getFocom() <em>Focom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFocom()
   * @generated
   * @ordered
   */
  protected Commands focom;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ForImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.FOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getFoexp()
  {
    return foexp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFoexp(Expression newFoexp, NotificationChain msgs)
  {
    Expression oldFoexp = foexp;
    foexp = newFoexp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.FOR__FOEXP, oldFoexp, newFoexp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFoexp(Expression newFoexp)
  {
    if (newFoexp != foexp)
    {
      NotificationChain msgs = null;
      if (foexp != null)
        msgs = ((InternalEObject)foexp).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FOR__FOEXP, null, msgs);
      if (newFoexp != null)
        msgs = ((InternalEObject)newFoexp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FOR__FOEXP, null, msgs);
      msgs = basicSetFoexp(newFoexp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.FOR__FOEXP, newFoexp, newFoexp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Commands getFocom()
  {
    return focom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFocom(Commands newFocom, NotificationChain msgs)
  {
    Commands oldFocom = focom;
    focom = newFocom;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.FOR__FOCOM, oldFocom, newFocom);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFocom(Commands newFocom)
  {
    if (newFocom != focom)
    {
      NotificationChain msgs = null;
      if (focom != null)
        msgs = ((InternalEObject)focom).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FOR__FOCOM, null, msgs);
      if (newFocom != null)
        msgs = ((InternalEObject)newFocom).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FOR__FOCOM, null, msgs);
      msgs = basicSetFocom(newFocom, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.FOR__FOCOM, newFocom, newFocom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.FOR__FOEXP:
        return basicSetFoexp(null, msgs);
      case MyDslPackage.FOR__FOCOM:
        return basicSetFocom(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.FOR__FOEXP:
        return getFoexp();
      case MyDslPackage.FOR__FOCOM:
        return getFocom();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.FOR__FOEXP:
        setFoexp((Expression)newValue);
        return;
      case MyDslPackage.FOR__FOCOM:
        setFocom((Commands)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FOR__FOEXP:
        setFoexp((Expression)null);
        return;
      case MyDslPackage.FOR__FOCOM:
        setFocom((Commands)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FOR__FOEXP:
        return foexp != null;
      case MyDslPackage.FOR__FOCOM:
        return focom != null;
    }
    return super.eIsSet(featureID);
  }

} //ForImpl
