/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import pret.myDsl.Commands;
import pret.myDsl.Expression;
import pret.myDsl.MyDslPackage;
import pret.myDsl.While;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>While</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link pret.myDsl.impl.WhileImpl#getWhexp <em>Whexp</em>}</li>
 *   <li>{@link pret.myDsl.impl.WhileImpl#getWhcom <em>Whcom</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WhileImpl extends MinimalEObjectImpl.Container implements While
{
  /**
   * The cached value of the '{@link #getWhexp() <em>Whexp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWhexp()
   * @generated
   * @ordered
   */
  protected Expression whexp;

  /**
   * The cached value of the '{@link #getWhcom() <em>Whcom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWhcom()
   * @generated
   * @ordered
   */
  protected Commands whcom;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WhileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.WHILE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getWhexp()
  {
    return whexp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWhexp(Expression newWhexp, NotificationChain msgs)
  {
    Expression oldWhexp = whexp;
    whexp = newWhexp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.WHILE__WHEXP, oldWhexp, newWhexp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWhexp(Expression newWhexp)
  {
    if (newWhexp != whexp)
    {
      NotificationChain msgs = null;
      if (whexp != null)
        msgs = ((InternalEObject)whexp).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WHILE__WHEXP, null, msgs);
      if (newWhexp != null)
        msgs = ((InternalEObject)newWhexp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WHILE__WHEXP, null, msgs);
      msgs = basicSetWhexp(newWhexp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WHILE__WHEXP, newWhexp, newWhexp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Commands getWhcom()
  {
    return whcom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWhcom(Commands newWhcom, NotificationChain msgs)
  {
    Commands oldWhcom = whcom;
    whcom = newWhcom;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.WHILE__WHCOM, oldWhcom, newWhcom);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWhcom(Commands newWhcom)
  {
    if (newWhcom != whcom)
    {
      NotificationChain msgs = null;
      if (whcom != null)
        msgs = ((InternalEObject)whcom).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WHILE__WHCOM, null, msgs);
      if (newWhcom != null)
        msgs = ((InternalEObject)newWhcom).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WHILE__WHCOM, null, msgs);
      msgs = basicSetWhcom(newWhcom, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WHILE__WHCOM, newWhcom, newWhcom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.WHILE__WHEXP:
        return basicSetWhexp(null, msgs);
      case MyDslPackage.WHILE__WHCOM:
        return basicSetWhcom(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.WHILE__WHEXP:
        return getWhexp();
      case MyDslPackage.WHILE__WHCOM:
        return getWhcom();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.WHILE__WHEXP:
        setWhexp((Expression)newValue);
        return;
      case MyDslPackage.WHILE__WHCOM:
        setWhcom((Commands)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.WHILE__WHEXP:
        setWhexp((Expression)null);
        return;
      case MyDslPackage.WHILE__WHCOM:
        setWhcom((Commands)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.WHILE__WHEXP:
        return whexp != null;
      case MyDslPackage.WHILE__WHCOM:
        return whcom != null;
    }
    return super.eIsSet(featureID);
  }

} //WhileImpl
